#-------------------------------
# General Site Settings

title: The Third Realm
description:  # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://a-rossetti.github.io" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
authors:
  andrea:
    author-name:   Andrea Rossetti
    author-avatar: andrea-author-avatar.jpg


#-------------------------------
# Contact links
twitter:   https://twitter.com/Andrea27172 # Twitter
github:    https://github.com/a-rossetti # Github
email:     rossettiandrea276@gmail.com # Email


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: Andrea27172 # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: github.us14.list-manage.com/subscribe/post?u=b361008367347aeefa28dbec8&amp;id=bcf1a34f6b&amp;f_id=00edb0e0f0 # Add your MailChimp form identifier


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
