name: Fetch X Posts

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - name: Fetch user ID
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          X_USERNAME: ${{ secrets.X_USERNAME }}
        run: |
          curl -X GET "https://api.twitter.com/2/users/by/username/$X_USERNAME" -H "Authorization: Bearer $BEARER_TOKEN" -o user.json
          USER_ID=$(jq -r '.data.id' user.json)
          echo "USER_ID=$USER_ID" >> $GITHUB_ENV

      - name: Fetch posts
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: |
          curl -X GET "https://api.twitter.com/2/users/$USER_ID/tweets" -H "Authorization: Bearer $BEARER_TOKEN" -o _data/x-posts.json

      - name: Commit posts
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add _data/x-posts.json
          git commit -m "Fetch latest posts from X"
          git push https://${{ secrets.PAT }}@github.com/a-rossetti/a-rossetti.github.io.git HEAD:master